esmero/ami

composer.json, src/AmiUtilityService.php, src/Entity/amiSetEntity.php
See #12 
Allison, please test with mixed set of local files, remote files from DSpace and Islandora to have a larger variety of use cases. This worked out fine for me.
The remote fetch also can follow up at least 5 redirects, so http or https is as good as it gets.
I removed the "required" ZIP upload from the AMI SET Edit Form. This allows users now to simply replace, from an existing SET the CSV (download, edit, remove the existing one, add the edited one) with an edited one. This way I could also add an Islandora datastream to an CSV that was fetching only from DSPACE without having to rebuild the SET. This is nice!
=> ISSUE-12: Fix file download from URL that provides an extension

ami.permissions.yml, ami.routing.yml, src/AmiBatchQueue.php, src/AmiUtilityService.php, src/Entity/Controller/amiSetEntityAccessControlHandler.php, src/Form/amiSetEntityDeleteProcessedForm.php, src/Form/amiSetEntityProcessForm.php, src/Plugin/QueueWorker/IngestADOQueueWorker.php
See #18 
This adds:
1.- Checks if `Content Moderation` is enabled and gets for chosen `Bundles` the valid workflows transitions for the current user.
2.- Shows Status Per Bundle. Even if a Bundle is not moderated we get a Publish/Unpublished option at least
3.- Removes the enqueue option for Delete Processed. Makes no sense to do that really (and can generate a Race condition)
4.- Adds a Naive validation for based settings i will move tomorrow into its own method (and make less naive). The idea here is that No Set gets ever processed without being sure data/config match.
5.- Adds 'moderation_status' during ingest in the Queue worker and falls back to Publish/Unpublish for unmoderated ones. Worst case always unpublished.
Still missing? If the ID passed as parent is numeric and not in …
=> ISSUE-18: Stricter validation and per bundle status/moderation option

src/AmiUtilityService.php, src/Form/AmiMultiStepIngest.php, src/Form/amiSetEntityDeleteProcessedForm.php
A bug. I was calling `->access()` on a non existing entry because ` loadByProperty` used to load ADOs from UUID returns an array keyed by the NODE ID, and not sequential (I knew this, but I'm tired)
Only then I can call ->access()
Gist: I was doing it wrong, assuming the ADO would be found on [0] entry in the array.
Introduced by #19 !
This fixes #22
=> ISSUE-22: Make sure we get the only ADO returned form the loadByProperty call.

src/AmiUtilityService.php, src/Form/AmiMultiStepIngest.php, src/Plugin/ImporterAdapter/SolrImporter.php, src/Plugin/ImporterAdapter/SpreadsheetImporter.php, src/Plugin/ImporterAdapterBase.php, src/Plugin/ImporterAdapterInterface.php
See #21 This is the second part, now full fledged with CSV header normalizer, cleaning out empty columns, parents, mapping for Compounds even if we DO not know what we will get and AMI Set creation at the end of the BATCH. Also some memory optimizations (this is heavy!)
- Better CSV header normalizing. WE get all fields first. The fetch. We keep track of the ones that actually have values per row. Once ready with the CSV we go back, make a diff on the headers and only keep the ones that are REALLY not empty and write a new clean CSV out.
- trying to get rid of authority_marcrelator fields (may need more work?)
- AMI set gets created and redirected to the Set.
Tested with 7000 Objects, took 25 seconds?
- Parent Object gets set into ismemberof
`@TODO`:
- Cleanups, probably more checks? Lots …
=> ISSUE-21b(the return of the CSV) Islandora 7 migrations! ready to be used (almost?)

src/Form/amiSetEntityProcessForm.php
See #34 
This just adds an extra check since drupal/core does not check for that.
@alliomeria @aksm
=> ISSUE-34: Fix Process AMI for non Moderated Entities on Drupal 9

src/Plugin/ImporterAdapter/SolrImporter.php
See #56  and #57 What a mess. I need vacations!
This applies the same logic to children rows and also fixes a totally wrong variable name inside the `::concatValues()` method
=> ISSUE-56b: Apply concat fix to children and also fix wrong var name

src/AmiUtilityService.php, src/Form/amiSetEntityReconcileForm.php
See #59 
PHP 8 fails seeking to a certain line (like in this case counting) because the flags passed are not taken in account, so it either returns 0 or a lot of lines. 
This was tested in PHP 8.0.16. To avoid writing double code i decided to take a naive approach and actually use fgetcsv() without return to move through the file since that function has no issues with our CSVs and JSON added data in cells (weird that seek() has). It works, tested on php 7.4 and 8.0.16
=> ISSUE-59: Offset ::csv_count(File $file) by 1 and get around PHP8 bug

src/AmiUtilityService.php, src/Form/amiSetEntityReconcileCleanUpForm.php, src/Plugin/QueueWorker/IngestADOQueueWorker.php
See #71 
Fixes various multiple files per Object as separate processes with remote downloads issues and timeouts  (now with proper timeout coming from PHP's max time) + smaller UI fixes on LoD Reconciliation Edit Form
There will be more work on this before 0.3.0 goes live but this is already a big moving forward
=> ISSUE-71: Fix eternal re-enqueueing and Download improvements

src/Plugin/QueueWorker/IngestADOQueueWorker.php
I made a big mistake on last pull re #71 (mistake has been around for a while) which totally skips Files IF not Forced to download them again when running it for a first time. Private stores that are empty return NULL
Comparing !(NULL) does not cast to FALSE?
=> ISSUE-71b: Wrong logic! Fixes non-sense issue of wrong comparisson

ami.services.yml, src/AmiUtilityService.php, src/Controller/AmiRowAutocompleteHandler.php, src/TwigExtension.php
See #74 
Includes now `{{ data_lod }}` into the Preview Functionality of AMI Sets including the actual data for the chose row and also empties (referential empties since those will not exist during the ingest, FYI, THAT IS GOOD believe me DO NOT FIGHT ME) 
and a new Twig Extension mean to be used ONLY for ingests and NOT in realtime calls.. I can even be "Dense" about this and cut it out in case the call is happening from an /ado/route .. ok? Be nice, only use it during ingest or donate to WIKIDATA and LoC
Uses one of these (there are a few more! but not documented yet...hehehe.. hint .. nominatim )
'loc;subjects;thing' => 'LoC subjects(LCSH)',
'loc;names;athing' => 'LoC Name Authority File (LCNAF)',
'loc;genreForms;thing' => 'LoC Genre/Form Terms (LCGFT)',
'loc;graphicMaterials;thing' => …
=> ISSUE-74: Improve AMI Sets Preview

src/AmiLoDService.php, src/Plugin/QueueWorker/IngestADOQueueWorker.php, src/TwigExtension.php
See #80 for the full explanation
This also adds reverse `nominatim` capabilities to our AMI LOD Service and to the extension of course in this form:
e.g usage is:
```Twig
{% set coordinates = "40.749778,-73.977618" %}
{% set nominatim = ami_lod_reconcile(coordinates, "nominatim;thing;reverse", "en", 1) %}
```
=> ISSUE-80: Make AMI LOD Twig extension signature more flexible

src/AmiBatchQueue.php, src/AmiLoDBatchQueue.php, src/AmiUtilityService.php, src/Controller/AmiRowAutocompleteHandler.php, src/Plugin/QueueWorker/IngestADOQueueWorker.php
See #84 and #83 
The largest thing here was the wrong extension/naming of remote files without a content disposition (which we neglected to use at all in 0.3.0 and 0.2.0 so was not even an issue). This will fix remotes coming from e.g `islandora/object/pid:1/OBJ/view` instead of download
There is an extra benefit on all of this, extensions are being normalized now if we know the mime type and I did a small optimization too!
@alliomeria @karomabiles hope this helps!
=> ISSUE-84 and ISSUE-83

src/AmiUtilityService.php
Well I did not solved the WHOLE issue on my last pull. This fixes the last warning `[$filename_from_remote_without_extension, $extensions_from_remote] = explode(".", $basename, 2);`
Is a bad idea if we do not know if there are actually  at least 2 part, so went the most traditional way with checks and more checks
=> ISSUE-84b: Files might not have an extension at all!

ami.module, src/AmiUtilityService.php, src/Entity/Controller/amiSetEntityAccessControlHandler.php, src/Entity/Controller/amiSetEntityListBuilder.php, src/Form/amiSetEntityDeleteProcessedForm.php
- Adds access checks for AMI Set delete processed ADOs operation (with caching for performance). If an AMI set's operation is 'update' or 'patch', do not show "Delete processed ADOs in the amiset/list operations column, and do not show the "Delete Processed ADO's" link when viewing an individual AMI Set.
- Make delete processed form always return a correctly formed drupal form (though I don't think we will ever see this version of the form now, so maybe we should just delete this part of the buildForm function).
See [ISSUE-67](https://github.com/esmero/ami/issues/67).
=> ISSUE-67 --> 0.3.0

src/Plugin/QueueWorker/IngestADOQueueWorker.php
See #90 
I was improperly checking the moderation state before deciding if I needed to ingest/update, leaving the following operation as an impossible
- Ingested as Draft
- Updated and made Published
This is a small fix that deals with Create/Update as separate cases. Tested
=> ISSUE-90: Fixes state/moderation when updating draft ingested Objects

src/Controller/AmiRowAutocompleteHandler.php
This permits accurate ami metadatadisplay template previewing if the user has implemented hook_format_strawberryfield_twigcontext_alter.
=> ISSUE-96 --- Invoke hook_format_strawberryfield_twigcontext_alter during AMI metadatadisplay preview

ami.module, ami.services.yml, src/AmiEventType.php, src/AmiLoDService.php, src/AmiUtilityService.php, src/Event/AmiCrudEvent.php, src/EventSubscriber/AmiEventPresaveSubscriber.php, src/EventSubscriber/AmiEventPresaveSubscriberProcessedLoDUpdater.php, src/Form/amiSetEntityForm.php, src/Form/amiSetEntityProcessForm.php, src/Form/amiSetEntityReconcileCleanUpForm.php, src/Form/amiSetEntityReconcileForm.php, src/Plugin/QueueWorker/IngestADOQueueWorker.php, src/Plugin/QueueWorker/LoDQueueWorker.php
See #93 
This pull adds new Update modes:
- 'update':  "Normal Update. Will update a complete existing ADO's configured target field with new JSON Content."
-  'replace' : "Replace Update. Will replace JSON keys found in an ADO's configured target field with new JSON content. Not provided ones will be kept"
- 'append': "Append Update. Will append values to existing JSON keys in an ADO's configured target field. New ones will be added too."
Adds also safety switch that keeps existing Files always safe and "undeletable" and "unreplaceable" but still allows new files to be added if Update or Append are used. 
JSON patching logging is going to be disabled by default until #92 is defined.
=> ISSUE-93: New Update logic

src/AmiUtilityService.php, src/Controller/AmiRowAutocompleteHandler.php, src/Form/amiSetEntityProcessForm.php, src/Plugin/Action/AmiStrawberryfieldCSVexport.php, src/Plugin/QueueWorker/IngestADOQueueWorker.php
See #99 and #100 
This also adds some AMI improvements for Updates when the source data from the CSV is lacking structure badly. I will have to iterate over and over this reality a few times but I feel I got it this time
=> ISSUE-100 and ISSUE-99: Fixes PHP8 issues (general)

src/AmiUtilityService.php, src/Controller/AmiRowAutocompleteHandler.php, src/Form/AmiMultiStepIngest.php, src/Plugin/ImporterAdapter/SolrImporter.php
See #107. 
- Adds adaptive Range/offset based on what was the last number of Top objects v/s Children Rations
- Copies CMODEL mapping between Children/Top objects during setup
- Validates UUID Mapping v/s Node to Node Mapping (to avoid those being mixed up)
- Multiple cleanups, fixes Automatic UUID for Plugins that run via Batch (e.g Solr)
@karomabiles and @alliomeria even if this is safer, I feel it just became a bit slower so will need you both to check with me during our call the same collection being harvested via your current systems v/s with this patch. I can do a pre-test just to be sure of course and make you loose less time
=> ISSUE-107: fix out of memory when fetching Top objects with lots of children

src/AmiUtilityService.php
See #113 
We try hard to reuse files and this now makes sure UUID is reused too. This of course opens the question of, and even if AMI users are power user,  should be allow file reuse without checking access? Or said differently, we can reuse, but maybe not change the owner? Still this fixes the problem and TBH this only will trigger if the source/destination are the same, means files coming from S3.
=> ISSUE-113: Preserve UUID when reusing a file

src/AmiUtilityService.php
See #115 
This fixes it. @alliomeria did some checks. I did some checks. All checks out. 
Eventually we might use a CSV library (a good colleague suggested this) but for now Vanilla CSV works.
=> ISSUE-115:Replace ::seek() with multiple ::next() to work around bug in PHP8/7/6/5

composer.json
See #124 
This fixes max version of VBO to 4.1.2 until we release 0.6.0 with changed signatures and we target 4.1.5 (4.1.4 and 4.1.3 are buggy)
=> ISSUE-124: VBO breaks after 4.1.2. Update composer.json in 0.4.0

composer.json
See #124 and https://github.com/esmero/ami/pull/125
@aksm same as before. Please merge as soon as you can?
=> ISSUE-124: VBO breaks after 4.1.2. Update composer.json in 0.5.0

ami.install, ami.links.task.yml, ami.module, ami.permissions.yml, ami.routing.yml, ami.services.yml, composer.json, src/AmiUtilityService.php, src/Breadcrumb/AmiSetBreadcrumbBuilder.php, src/Entity/Controller/amiSetEntityListBuilder.php, src/Entity/amiSetEntity.php, src/EventSubscriber/AmiStrawberryfieldEventPresaveSubscriberJsonTransform.php, src/Form/AmiMultiStepIngestBaseForm.php, src/Form/amiSetEntityDeleteProcessedForm.php, src/Form/amiSetEntityProcessForm.php, src/Form/amiSetEntityReportForm.php, src/Plugin/ImporterAdapter/SolrImporter.php, src/Plugin/QueueWorker/IngestADOQueueWorker.php
See #8 
This involves
- New AMI Set Field where we will attach a CSV and/or append records to it on each processing
- Reports Tab where you can see by type/filter/alerts/info about the last processed set matching also 1:1 to the actual CSV data (so label/node_uuid, etc will match too + timestamp, what happened, why, etc)
- A new option for processing (enabled by default) that will skip processing a ROW leading to an ADO if any of the file processing/downloading/fetching fails. (missing file, remote disconnects, etc)
@karomabiles @alliomeria keeping you in the loop. This is my first pass, will finish ~tomorrow~ someday. Should have done this sooner!
ps:awwwwwwwww
=> ISSUE-8: Add CSV reporting + Skip on missing file(s)

composer.json, src/AmiUtilityService.php, src/Controller/AmiRowAutocompleteHandler.php, src/Form/amiSetEntityDeleteProcessedForm.php, src/Plugin/QueueWorker/IngestADOQueueWorker.php
See #129 
This also adds:
- JSON Pretty printing to AMI Set previews that generate (of course) JSON when the "use destination format" check is enabled
- Redirects user to "process" tab after running a "delete processed"
@aksm could you give this a small look?
=> ISSUE-129: Better remote Filename handling and small improvements

src/Form/amiSetEntityReportForm.php
See #131 
This fixes a white screen/exception when accessing existing reports (generated e.g via a previous hash of 0.5.0) but without yet a status report generated from a Batch Processing. My bad.
=> ISSUE-131: Fix wrong logic. Status might not be preset (yet)

src/Controller/AmiRowAutocompleteHandler.php
See #136 
We are not even using #description but seems like #description_display IS required. Will test more
=> ISSUE-136: Adds '#description_display' => 'before' to avoid warning

src/AmiUtilityService.php
See #138. Tested. Works. 
- Cuts from the center of the file name to allow consistent Natural Order sorting if that is needed.
- Cuts both URI and Filename (if needed) independently.
- adds cute emoji (ascii) in between that should not "disturb" even the most purist filename advocates.
=> ISSUE-138: Caps filename and uri to Drupal's File Entity build in limits

src/AmiUtilityService.php
See #159 
This is a simple regular expression: `'/^(\.|\h)*/m'` It will match any combination of `dots` and horizontal spaces from the beginning. To be extra safe, after cleaning we check if anything is left and if not we actually default the the URL given name...
I only do this for Names provided by a header/remove HTTP idea. If a user decides to use local filenames or S3 ones, we don't want to modify their names at all (like really) and again, good practices are not something we SHOULD enforce via code. This is a way of getting around the strange filenames we are getting from remote sources.
Relates to https://github.com/esmero/strawberryfield/pull/266 which deals with actual filenames that have dots
=> ISSUE-159: Remove spaces and dots from the beginning in any combination for remote filenames

src/Plugin/QueueWorker/IngestADOQueueWorker.php
See #171 
This covers the uncaught issue on #171. Also makes sure that when the AMI set is gone we log into the standard Drupal (DB) logger instead of the AMI specific file one (monolog)
=> ISSUE-171: Check for AMI existence. In case it was delete or exception log to DB

src/EventSubscriber/AmiFacetsViewsBulkOperationsEventSubscriber.php, src/Plugin/Action/AmiStrawberryfieldCSVexport.php, src/Plugin/facets/processor/VboBatchProcessorHandler.php
See #177 
This solves our part of the issue but, sadly, as I explored the world of non-sense, long Machine names (creating the longest Drupal allowed me to) I broke VBO.
See this here https://git.drupalcode.org/project/views_bulk_operations/-/blob/4.2.x/src/ViewsBulkOperationsBatch.php#L76
Basically VBO does the same, concatenates this blindly, breaking when the sum of a Views Machine name + a Display exceeds the very tiny Drupal Name for a temporary storage collection...
@alliomeria @aksm the world of OSS is hard.
=> ISSUE-177: of long Views and Display Machine names. 

src/Form/amiSetEntityReportForm.php
See #190 
Adds a 'max-age' 0 to the #cache entry in the Reports form
=> ISSUE-190: Set max-age to 0 for amiSetEntityReportForm.php

src/EventSubscriber/AmiFacetsViewsBulkOperationsEventSubscriber.php
See #197 
Since Drupal 10.2 we can't no longer just relay on a 'op' in the input to avoid saving in our VBO temporary storage facets and filters. 
This new approach here attempts first to check if the `VBO` operation is happening under the actual Views `ROUTE` (so the page that the views handles) OR, if someone is using layout builder/a block, if 'op' != 'do' (might be another moving target) and there is no batch id.
How I covered VBO with facets running as a block is probably not the cleanest way but for now is solid enough
@davidbasswwu @alliomeria will ping you when the block option is tested and all is merged
=> ISSUE-197: Deals with moving target for our VBO Event subscriber conditionals

src/Form/AmiMultiStepIngest.php, src/Form/amiSetEntityProcessForm.php, src/Plugin/ImporterAdapter/EADImporter.php, src/Plugin/ImporterAdapter/GoogleSheetImporter.php, src/Plugin/ImporterAdapter/SolrImporter.php, src/Plugin/ImporterAdapterBase.php, src/Plugin/ImporterAdapterInterface.php, src/Plugin/QueueWorker/CsvADOQueueWorker.php, src/Plugin/QueueWorker/IngestADOQueueWorker.php
See #195 . 
Includes.
-  Opinionated EAD Importer. Uses our script. @alliomeria we should publish our scripts (scrapbook/MODS one and this one in another repo)
- CSVs are enqueued now. What does that mean? A new Background processor but also not waiting for a CSV to be actually processed in real time when sending to the backend. Safer, faster
- Fixes in the queue worker, better checks and also ap:tasks are preserved see #200
=> ISSUE-195: CSV queue worker and nested CSVs for EAD + an EAD plugin

src/EventSubscriber/AmiFacetsViewsBulkOperationsEventSubscriber.php, src/Plugin/ImporterAdapter/SolrImporter.php
This adds `scheme` to config. Also add some more info so we can debug when things fail *(under all fields)
and also fixes the checkboxes (foreach) deprecation on NULL that popped un in the logs for the Solr Importer
Also deals with #207 
@alliomeria ping
=> ISSUE-205: Allow SSL + fix Drupal 10.3.1 exception when layout builder is disabled

src/AmiUtilityService.php
Use the AMI set user ID for checking access to entity operations in AmiUtilityService::preprocessAmiSet and AmiUtilityService::getProcessedAmiSetNodeUUids. Fixes cases where the process is executing under cron or hydroponics and the user is anonymous.
=> ISSUE-214 --->0.8.0

src/AmiUtilityService.php, src/Form/amiSetEntityDeleteProcessedForm.php, src/Form/amiSetEntityProcessForm.php
=> ISSUE-217: Ensures info['uid'] to be present for both processing options

src/AmiUtilityService.php, src/Plugin/QueueWorker/IngestADOQueueWorker.php
(was User one before.. which is really a warning)
This wraps just around AMI Metadata Display processing a catch/try and logs an error. Will handle it returning NULL the same way it would do for improper JSON or invalid template (non existing)
@patdunlavey now your job is to properly test this against the same data/metadata combo you had failed/re-enqueuing forever and let me know if this needs more changes.
I would love to do that here really \Drupal\format_strawberryfield\Entity\MetadataDisplayEntity::renderNative at the source itself .. BUT ... we would not be able to run Metadata Display previews at all if I did that..
I will work on a refactor of the base methods and will try an override of the new Drupal Default Twig HTML filter that is where this whole mess started
=> ISSUE-221: Drupal 10.2.8+ throws error on Array render 

src/AmiUtilityService.php
See #201 
This new approach (i will test more during the weekend) tries to ensure, in an as efficient as possible manner, that parent Objects (at any level) get ingested before children objects, specially complex when using UUIDs instead of ROW IDs. The code is cleaner @alliomeria and more generalized to treat also the combination of ROW IDs and UUIDs at the same time in a single AMI set CSV
This also removes `::isRootParent()` since it was only useful for CSV Row IDS... and generated false positives of "a Root" object for anything that had a UUID. Now `::getParentRowId()` will return FALSE if the parent is invalid, NULL if it is the ROOT and a number of course if present
=> ISSUE-201: Complete refactor on Sorting/dependency Algorithm for AMI set

src/Plugin/Action/AmiStrawberryfieldJsonAsWebform.php, src/Plugin/QueueWorker/IngestADOQueueWorker.php
See #230 
I will explain/provide examples of this tomorrow *during office hours
=> ISSUE-230: Make update - append Operations - more consistent and protect label and type

src/AmiBatchQueue.php, src/AmiUtilityService.php, src/Form/amiSetEntityDeleteProcessedForm.php, src/Form/amiSetEntityProcessForm.php, src/Plugin/ImporterAdapter/EADSyncImporter.php, src/Plugin/QueueWorker/CsvADOQueueWorker.php, src/Plugin/QueueWorker/IngestADOQueueWorker.php
See #236 
Also adds UUID V4 AMI set Step validation for EAD Sync and also some "wrong CSV/empty CSV" fall backs.
I have to be honest here: The AMI EAD SYNC plugin requires a very specific reality (Metadata/structure) and understanding that the actual "I will sync on the current state of the repo" happens once, during the AMI set setup. Any larger change on ADOs that happens after that, before the EAD Sync runs might lead to an inconsistent *or unexpected* result. Be aware of that. There is no way modifying/updating/deleting 10K objects in a pass can NOT be a "be careful/think/plan" operation.
Also solves the warning of non initialized variable $skip in the CSV expander
=> ISSUE-236: Unmoderated Status improvements/bug fixes and new "Sync/Update" option
